#!/usr/bin/env python3
from pathlib import Path
import json, hashlib, re, sys
R=Path(__file__).resolve().parents[1]
checks=[]
def ck(name, cond, detail=''):
    checks.append((name,bool(cond),detail))
    if not cond: print('FAIL',name,detail)

manifest=(R/'app/src/main/AndroidManifest.xml').read_text(encoding='utf-8')
build=(R/'app/build.gradle').read_text(encoding='utf-8')
main=(R/'app/src/main/java/com/medipharm/medref/MainActivity.java').read_text(encoding='utf-8')
runtime=(R/'app/src/main/java/com/medipharm/medref/MedRefDataRuntime.java').read_text(encoding='utf-8')
server=(R/'app/src/main/java/com/medipharm/medref/LocalContentServer.java').read_text(encoding='utf-8')
db=(R/'app/src/main/java/com/medipharm/medref/MedRefDatabase.java').read_text(encoding='utf-8')
html=(R/'app/src/main/assets/web/index.html').read_text(encoding='utf-8')
boot=(R/'app/src/main/assets/web/assets/offline-bootstrap.js').read_text(encoding='utf-8')
ck('package', "applicationId 'com.medipharm.medref'" in build)
ck('app_name', '<string name="app_name">MedRef</string>' in (R/'app/src/main/res/values/strings.xml').read_text())
ck('min_sdk_31', 'minSdk 31' in build)
ck('target_sdk_35', 'targetSdk 35' in build and 'compileSdk 35' in build)
ck('version_1_0_7', "versionName '1.0.7'" in build and 'versionCode 10007' in build)
ck('local_origin', 'app.medref.local' in server and 'app.medref.local' in boot)
ck('sqlite_runtime', 'SQLiteDatabase' in db and 'medref.db' in runtime)
ck('sqlite_pragma_api', 'execSQL("PRAGMA journal_mode=WAL")' not in db and 'enableWriteAheadLogging()' in db and 'rawQuery("PRAGMA synchronous=NORMAL"' in db)
ck('source_media_sha_router', 'SOURCE_MEDIA_PATTERN' in server and 'resolveLocalSourceMedia' in server and '300x' not in '')
ck('native_login_modal', 'CredentialStore' in main and 'ĐĂNG KÝ TÀI KHOẢN' in main and 'Hiện mật khẩu' in main and 'Lưu thông tin đăng nhập' in main)
ck('sync_ux_refresh', 'Đang đồng bộ dữ liệu' in main and 'MedRef đang chuẩn bị dữ liệu phác đồ' in main)
ck('foldable_window_insets', 'WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout()' in main and 'onConfigurationChanged' in main and 'applySystemInsets' in main)
ck('official_update_endpoint', 'wp-json/medipharm-reference/v1/medref/app-version' in build and 'fetchUpdateManifest' in main)
ck('github_update_fallback', 'raw.githubusercontent.com/lesangmd/Medref/main/medref-update.json' in main)
ck('about_user_facing', 'Giới thiệu MedRef' in main and 'Tra cứu Phác đồ điều trị' in main and 'rollback previous-good' not in main)
css=(R/'app/src/main/assets/web/assets/mcr-app.css').read_text(encoding='utf-8')
ck('account_popover_layout', 'MedRef Android v1.0.5 · Account popover geometry' in css and 'white-space:nowrap!important' in css and 'justify-content:flex-start!important' in css)
ck('session_reauth_no_full_hydration', 'reauthenticateAndOpen' in main and 'dataRuntime.reauthenticate' in main and 'if(dataRuntime!=null&&dataRuntime.hasActiveData())reauthenticateAndOpen()' in main)
ck('legacy_manifest_migration', 'legacy_data_version' in runtime and 'migrateLocalManifestVersion' in runtime)
ck('update_preflight_dialog', 'checkDataUpdateInteractive' in main and 'Có dữ liệu MedRef mới' in main and 'Dữ liệu đã cập nhật' in main)
ck('dataset_selective_refresh', 'checkForUpdates' in runtime and 'refreshDatasetsWithManifest' in runtime and 'changedDatasets' in runtime)
ck('media_in_place_delta', 'List<JSONObject> changed=new ArrayList<>()' in runtime and 'hydrateMediaParallel(changed' in runtime and 'media-staging' not in runtime)
ck('dataset_compat_signature', 'compatSignature' in db and 'clearDataset' in db)
ck('credential_store_file', (R/'app/src/main/java/com/medipharm/medref/CredentialStore.java').is_file())
ck('slots', all(x in runtime for x in ['active','staging','previous-good']))
ck('30_day_session', '30L * 24L * 60L * 60L * 1000L' in runtime)
ck('authenticated_snapshot', '/wp-json/medipharm-reference/v1/offline/' in runtime and 'X-WP-Nonce' in runtime)
ck('sha_media', 'SHA-256 media không khớp' in runtime and 'MessageDigest.getInstance("SHA-256")' in runtime)
ck('media_catalog_rehydrate', 'remoteMedia' in runtime and 'localMedia' in runtime and 'media' in runtime)
ck('media_bundle_transport', 'bundle_url' in runtime and 'ZipInputStream' in runtime and 'hydrateMediaBundles' in runtime)
ck('verified_media_cache', 'verified-media-cache' in runtime and 'findReusableMedia' in runtime)
ck('media_retry', 'downloadToFileWithRetry' in runtime and 'maxAttempts' in runtime)
ck('media_parallel_fallback', 'Executors.newFixedThreadPool' in runtime and 'hydrateMediaParallel' in runtime)
ck('native_actions', all(x in main for x in ['"medref".equals(scheme)','data-update','rollback-data','check-update']))
ck('web_assets', all((R/'app/src/main/assets/web/assets'/x).is_file() for x in ['mcr-app.css','mcr-app.js','mtp-app.css','mtp-app.js','nah-icd10.css','nah-icd10.js','offline-bootstrap.js']))
ck('web_roots', all(x in html for x in ['id="mcr-app"','id="mtp-app"','data-nah-icd10-app']))
ck('no_cleartext', 'usesCleartextTraffic="false"' in manifest)
ck('no_mdict_package_residue', 'com.medipharm.mdict' not in ''.join([main,runtime,server,db,build,manifest,boot]))
summary={'release':'MedRef Android v1.0.7','checks':len(checks),'passed':sum(x[1] for x in checks),'failed':[x[0] for x in checks if not x[1]],'status':'PASS' if all(x[1] for x in checks) else 'FAIL'}
(R/'QA-v1.0.0.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps(summary,ensure_ascii=False))
sys.exit(0 if summary['status']=='PASS' else 1)
